### PR TITLE
Remove new column types

### PR DESCRIPTION
**Pull request by mitchwadair**
This PR just removes the new column types we added. They will be added back as separate PRs that we can add onto the MVP

Did not include BSON since there is another PR related. Do we want to also remove that to re-add in full on that PR?

### CODE REVIEW

**Comment by Rodriguespn** [comment]
@mitchwadair I think it makes sense to remove the BSON column and then add it later. Less code means less likelihood of having bugs

**Comment by Rodriguespn** [comment]
nit: remove the unsupported types from `drizzle-orm/src/singlestore-core/columns/index.ts`

**Review by Rodriguespn — COMMENTED** [review]
LGTM :+1: 
You can also remove BSON type columns, we'll add it later

nit: remove the unsupported types from `drizzle-orm/src/singlestore-core/columns/index.ts`

**Comment by mitchwadair** [comment]
> @mitchwadair I think it makes sense to remove the BSON column and then add it later. Less code means less likelihood of having bugs

oh yes good call. Totally forgot about that

**Review by Rodriguespn — APPROVED** [review]

**Pull request merged**
